### PR TITLE
Small fixes

### LINKED ISSUE #53: Don't Send Passcode as Raw String
Only sending as a raw string for development. Change it to send a token when done dev.

### PR DESCRIPTION
**Pull request by Pav0l**
# Description

- Removed `passcode` from response object
- Added condition for `checkPlanLegibility` routing

Fixes #53 

## Type of change

Please add a relevant label.

## Change status

- [x] Complete, tested, ready to review and merge

# How Has This Been Tested?

Please describe steps taken to ensure this feature is functional and does not break other features:

Tested manually.

# Checklist:

- [x] My code follows the style guidelines of this project

- [x] I have performed a self-review of my own code

- [x] I have commented my code, particularly in hard-to-understand areas

- [x] I have made corresponding changes to the documentation, if relevant

- [x] I have run the app using my feature and ensured that no functionality is broken

- [x] My changes generate no new warnings

- [x] There are no merge conflicts

### CODE REVIEW

File: utils/checkPlanLegibility.js [hunk 1]
```diff
@@ -5,8 +5,12 @@ const PAYMENT_PLANS = require('./PAYMENT_PLANS');
 
 const checkPlanLegibility = async (hotel_Id, newPlan) => {
   try {
-    // const staff = await axios.get(`http://localhost:7000${path.users}?hotel_id=${hotel_Id}`);
-    const staff = await axios.get(`${url}${path.users}?hotel_id=${hotel_Id}`);
+    const staff =
+      process.env.NODE_ENV === 'development'
+        ? await axios.get(
```
Comment (mark-marshall) [inline utils/checkPlanLegibility.js:10]: Nice!

**Review by mark-marshall — APPROVED** [review]
